---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: pihole-admin
  namespace: pihole
spec:
  encryptedData:
    password: AgBE0WH/n7H1yIzuEEyESHfrNjsFaFXeFHWh/9oKDrp5hXO5LcWeDdABth2u8GV8ZTQhkmdd3IDCSz7XxPFS6guAzYarp5kHnes1DlS+zJVDhwkxtryAfk99PtwHYdlHxlYqv66ryQF+cd1guhMwytHtMkmH+jK/0s9ofOPg0lrKvp1WUfvmJOF4R9OkwXhqX6kk7azbVgdBS3SN3tqlqZVEBSiQ7jqU03AytIahVSG1gyZma2Uu9exOF11tzf+wL+AcMOGxofiAfDVxQao2EjPTCa5HFB+adOI3EBAOZBxP5ipzfl/36GjSjmd6gabEXSeQ/GKuoec5er2Lxn5UEkckrRYolY6EmvZegmKe1i0Gj5MrmG0XedJSRlQwkVXIsBLbJqrbqtIBXrtLUBS3GPQBT5cauGvP0RH6kEHjEos9TmvF096TCoBu9rwe5QM+V6BfAK2w7z5Fudfo4G3+uMPLnkuhmTg4TrKrqIGkw9mISNCX5HJsJNomccxaVhdDCqpGvb0s3yzWd8Nb5AJTTT58TSnWgcfmxkpWoiH7WadS0fdz1bdnUlqvWBfqMQznE2kYciRh9GwJn1vbcqPIqBQ4Tw5euefKKERIA17x2elkIcNNb7ikgXIpxsYafRZg2ckPkMiWbdiWP7JXpNA1tHwbjapQceN88Q1vHFKBoTmDX9gTtJBRI5C1Fz9ep+InNbs99VecDrDB64VIYBUlngiSTdKMrNgY1ucJJsCfLfJ1
  template:
    metadata:
      name: pihole-admin
      namespace: pihole
