{{- if not .Values.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "pihole.fullname" . }}
  labels:
    {{- include "pihole.labels" . | nindent 4 }}
type: Opaque
data:
  password: {{ .Values.adminPassword | b64enc | quote }}
{{- end }}
