apiVersion: v1
kind: Service
metadata:
  name: {{ include "pihole.fullname" . }}-web
  labels:
    {{- include "pihole.labels" . | nindent 4 }}
  {{- with .Values.serviceWeb.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.serviceWeb.type }}
  selector:
    {{- include "pihole.selectorLabels" . | nindent 4 }}
  ports:
    - name: http
      port: {{ .Values.serviceWeb.port }}
      targetPort: http
      protocol: TCP
