apiVersion: v1
kind: Service
metadata:
  name: {{ include "pihole.fullname" . }}-dns
  labels:
    {{- include "pihole.labels" . | nindent 4 }}
  {{- with .Values.serviceDNS.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.serviceDNS.type }}
  {{- with .Values.serviceDNS.loadBalancerIP }}
  loadBalancerIP: {{ . }}
  {{- end }}
  {{- if and (eq .Values.serviceDNS.type "LoadBalancer") .Values.serviceDNS.externalTrafficPolicy }}
  externalTrafficPolicy: {{ .Values.serviceDNS.externalTrafficPolicy }}
  {{- end }}
  {{- with .Values.serviceDNS.ipFamilies }}
  ipFamilies:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- with .Values.serviceDNS.ipFamilyPolicy }}
  ipFamilyPolicy: {{ . }}
  {{- end }}
  selector:
    {{- include "pihole.selectorLabels" . | nindent 4 }}
  ports:
    - name: dns-udp
      port: 53
      targetPort: dns-udp
      protocol: UDP
    - name: dns-tcp
      port: 53
      targetPort: dns-tcp
      protocol: TCP
